
server:
  port: 8083

# 数据池设置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/food?serverTimezone=GMT%2B8&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&allowPublicKeyRetrieval=trueh
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
