rabbitComponent:
  exchange:
    deliveryman: exchange.order.deliveryman
    dlx: exchange.dlx
  queue:
    deliveryman: queue.deliveryman
  routingKey:
    deliveryman: key.deliveryman
    order: key.order
    dlx: \#

